# Generated by Django 5.2.7 on 2025-12-22 23:33

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_remove_course_antirequisite_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('units_required', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('requirement_type', models.CharField(choices=[('group', 'Group'), ('checkbox', 'Checkbox')], max_length=8)),
                ('num_courses_required', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='checklists.additionalconstraint')),
                ('target_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_constraints', to='checklists.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalConstraintAllowedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(related_name='+', to='courses.course')),
                ('target_checkbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_courses', to='checklists.additionalconstraint')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_type', models.CharField(choices=[('head', 'Head'), ('group', 'Group'), ('checkbox', 'Checkbox')], max_length=8)),
                ('title', models.CharField(max_length=64)),
                ('units_required', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='checklists.checklistnode')),
                ('target_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='checklists.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='CheckboxAllowedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(related_name='+', to='courses.course')),
                ('target_checkbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_courses', to='checklists.checklistnode')),
            ],
        ),
        migrations.CreateModel(
            name='NonCourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_course_requirements', to='checklists.checklist')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='checklists.specialization'),
        ),
        migrations.AddConstraint(
            model_name='additionalconstraint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('requirement_type', 'group'), _negated=True), ('num_courses_required__isnull', True)), models.Q(('requirement_type', 'group'), ('num_courses_required__isnull', False)), _connector='OR'), name='only_group_has_courses_required'),
        ),
        migrations.AddConstraint(
            model_name='checklistnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('requirement_type', 'group'), _negated=True), ('units_required__isnull', True)), models.Q(('requirement_type', 'group'), ('units_required__isnull', False)), _connector='OR'), name='only_group_has_units_required'),
        ),
    ]
