# Generated by Django 5.2.7 on 2025-12-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='additionalconstraint',
            name='only_group_has_courses_required',
        ),
        migrations.AddConstraint(
            model_name='additionalconstraint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('requirement_type', 'group'), _negated=True), ('num_courses_required__isnull', True)), models.Q(('requirement_type', 'group'), ('num_courses_required__isnull', False)), _connector='OR'), name='only_group_has_courses_required'),
        ),
    ]
