# Generated by Django 5.2.7 on 2025-12-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_remove_additionalconstraint_only_group_has_courses_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
    ]
