# Generated by Django 5.2.7 on 2025-12-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_specialization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
