# Generated by Django 5.2.7 on 2025-12-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_alter_specialization_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistnode',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
