# Generated by Django 5.2.7 on 2025-12-22 23:33

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        ('courses', '0002_remove_course_antirequisite_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('units_required', models.PositiveSmallIntegerField()),
                ('taken_course_units', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('planned_course_units', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('original_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='checklists.checklist')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='checklists.specialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdditionalConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('requirement_type', models.CharField(choices=[('group', 'Group'), ('checkbox', 'Checkbox')], max_length=8)),
                ('num_courses_required', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('num_courses_gathered', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('original_checkbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='checklists.additionalconstraint')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='progress.useradditionalconstraint')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_contraints', to=settings.AUTH_USER_MODEL)),
                ('target_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_constraints', to='progress.userchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='UserChecklistNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_type', models.CharField(choices=[('head', 'Head'), ('group', 'Group'), ('checkbox', 'Checkbox')], max_length=8)),
                ('title', models.CharField(max_length=64)),
                ('units_required', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('units_gathered', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('original_checkbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='checklists.checklistnode')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='progress.userchecklistnode')),
                ('selected_course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.course')),
                ('target_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='progress.userchecklist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_nodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_list', models.CharField(choices=[('taken', 'Taken'), ('planned', 'Planned'), ('wishlist', 'Wishlist')], max_length=16)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCoursePathNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisite_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='courses.courserequisitenode')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='progress.usercourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_paths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDepthList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_chain', models.BooleanField(blank=True, null=True)),
                ('total_units', models.PositiveSmallIntegerField(default=0)),
                ('num_courses', models.PositiveSmallIntegerField(default=0)),
                ('courses', models.ManyToManyField(blank=True, related_name='depth_lists', to='progress.usercourse')),
                ('target_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depth_list', to='progress.userchecklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depth_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userchecklist',
            constraint=models.UniqueConstraint(fields=('user', 'specialization'), name='unique_specialization_per_user'),
        ),
        migrations.AddConstraint(
            model_name='useradditionalconstraint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('requirement_type', 'checkbox'), ('num_courses_required__isnull', True), ('num_courses_gathered__isnull', True)), models.Q(('requirement_type', 'group'), ('num_courses_required__isnull', False), ('num_courses_gathered__isnull', False)), _connector='OR'), name='only_groups_have_courses'),
        ),
        migrations.AddConstraint(
            model_name='useradditionalconstraint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('requirement_type', 'checkbox'), _negated=True), ('original_checkbox__isnull', True)), models.Q(('requirement_type', 'checkbox'), ('original_checkbox__isnull', False)), _connector='OR'), name='only_checkboxes_have_checkbox_field'),
        ),
        migrations.AddConstraint(
            model_name='userchecklistnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('requirement_type', 'group'), _negated=True), ('units_required__isnull', True), ('units_gathered__isnull', True)), models.Q(('requirement_type', 'group'), ('units_required__isnull', False), ('units_gathered__isnull', False)), _connector='OR'), name='only_groups_have_units'),
        ),
        migrations.AddConstraint(
            model_name='userchecklistnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('requirement_type', 'checkbox'), _negated=True), ('original_checkbox__isnull', True), ('selected_course__isnull', True)), models.Q(('requirement_type', 'checkbox'), ('original_checkbox__isnull', False), ('selected_course__isnull', False)), _connector='OR'), name='only_checkboxes_have_course_and_checkbox_field'),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['user', 'course_list'], name='progress_us_user_id_80ab91_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercourse',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_course_per_user'),
        ),
        migrations.AddIndex(
            model_name='usercoursepathnode',
            index=models.Index(fields=['user', 'target_course', 'path'], name='progress_us_user_id_e755ad_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoursepathnode',
            index=models.Index(fields=['user', 'target_course', 'depth'], name='progress_us_user_id_1f3d44_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercoursepathnode',
            constraint=models.UniqueConstraint(fields=('user', 'target_course'), name='unique_target_course_per_user'),
        ),
    ]
