# Generated by Django 5.2.7 on 2025-12-26 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_courserequisitenode_leaf_course_and_more'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoursepathnode',
            name='requisite_node',
        ),
        migrations.AddField(
            model_name='usercoursepathnode',
            name='prerequisite_node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_paths', to='courses.courseprerequisitenode'),
            preserve_default=False,
        ),
    ]
