# Generated by Django 5.2.7 on 2025-12-28 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_alter_checklistnode_title'),
        ('courses', '0006_alter_course_category'),
        ('progress', '0002_remove_usercoursepathnode_requisite_node_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userchecklistnode',
            name='only_checkboxes_have_course_and_checkbox_field',
        ),
        migrations.AlterField(
            model_name='useradditionalconstraint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_contraints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userchecklistnode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userchecklistnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('requirement_type', 'checkbox'), _negated=True), ('original_checkbox__isnull', True), ('selected_course__isnull', True)), models.Q(('requirement_type', 'checkbox'), ('original_checkbox__isnull', False)), _connector='OR'), name='only_checkboxes_have_checkbox_field'),
        ),
    ]
