# Generated by Django 5.2.7 on 2025-12-28 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_alter_checklistnode_title'),
        ('courses', '0007_alter_course_antirequisites_and_more'),
        ('progress', '0003_remove_userchecklistnode_only_checkboxes_have_course_and_checkbox_field_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userchecklistnode',
            name='only_checkboxes_have_checkbox_field',
        ),
        migrations.AlterField(
            model_name='userchecklistnode',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='userchecklistnode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('requirement_type', 'checkbox'), _negated=True), ('original_checkbox__isnull', True), ('selected_course__isnull', True)), models.Q(('requirement_type', 'checkbox'), ('original_checkbox__isnull', False)), _connector='OR'), name='only_checkboxes_have_checkbox_field_checklist'),
        ),
    ]
