# Generated by Django 5.2.7 on 2025-12-28 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_antirequisites_and_more'),
        ('progress', '0004_remove_userchecklistnode_only_checkboxes_have_checkbox_field_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionalconstraint',
            name='selected_course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.course'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='prereqs_met',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='usercourse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course_list', 'taken'), _negated=True), ('prereqs_met__isnull', True), _connector='OR'), name='taken_courses_have_null_prereqs_met'),
        ),
    ]
