# Generated by Django 5.2.7 on 2025-12-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_useradditionalconstraint_selected_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursepathnode',
            name='branch_completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
