# Generated by Django 5.2.7 on 2025-12-30 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_antirequisites_and_more'),
        ('progress', '0006_usercoursepathnode_branch_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercoursepathnode',
            name='unique_target_course_per_user',
        ),
        migrations.RemoveIndex(
            model_name='usercoursepathnode',
            name='progress_us_user_id_e755ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='usercoursepathnode',
            name='progress_us_user_id_1f3d44_idx',
        ),
        migrations.RemoveField(
            model_name='usercoursepathnode',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='usercoursepathnode',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='usercoursepathnode',
            name='path',
        ),
        migrations.AddField(
            model_name='usercoursepathnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='progress.usercoursepathnode'),
        ),
        migrations.AlterField(
            model_name='usercoursepathnode',
            name='branch_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='usercoursepathnode',
            index=models.Index(fields=['user', 'target_course', 'parent'], name='progress_us_user_id_dfbe55_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercoursepathnode',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('user', 'target_course'), name='unique_root_per_user_course'),
        ),
    ]
