# Generated by Django 5.2.7 on 2026-01-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_antirequisites_and_more'),
        ('progress', '0007_remove_usercoursepathnode_unique_target_course_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchecklistnode',
            name='selected_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.course'),
        ),
    ]
