# Generated by Django after data migration
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_migrate_course_to_usercourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchecklistnode',
            name='selected_course',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='progress.usercourse'
            ),
        ),
    ]
