# Generated by Django 5.2.7 on 2026-01-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0010_alter_userchecklistnode_selected_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchecklist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
