# Generated by Django 5.2.7 on 2025-11-24 15:51

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=8)),
                ('number', models.CharField(max_length=8)),
                ('units', models.PositiveSmallIntegerField()),
                ('offered_next_term', models.BooleanField(null=True)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('math', 'Math'), ('cs', 'CS'), ('hum', 'Humanities'), ('ss', 'Social Sciences'), ('ps', 'Pure Sciences'), ('as', 'Applied Sciences'), ('comm1', 'Communications List 1'), ('comm2', 'Communications List 2')], max_length=32), blank=True, default=list, size=None)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('prerequisite_text', models.TextField()),
                ('corequisite_text', models.TextField()),
                ('antirequisite_text', models.TextField()),
                ('num_uwflow_ratings', models.PositiveSmallIntegerField()),
                ('uwflow_liked_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('uwflow_easy_ratings', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('uwflow_useful_ratings', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['category'], name='courses_cou_categor_ed2d8d_gin')],
                'unique_together': {('code', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CourseRequisiteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisite_type', models.CharField(choices=[('pre', 'Prerequisite'), ('co', 'Corequisite'), ('anti', 'Antirequisite')], max_length=16)),
                ('node_type', models.CharField(choices=[('group', 'Group'), ('course', 'Course')], max_length=8)),
                ('num_children_required', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('leaf_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='courses.course')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.courserequisitenode')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_nodes', to='courses.course')),
            ],
            options={
                'indexes': [models.Index(fields=['target_course', 'requisite_type', 'parent'], name='courses_cou_target__9041a6_idx'), models.Index(fields=['tree_id', 'lft'], name='courses_courserequisitenod5d01')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('node_type', 'course'), ('leaf_course__isnull', False), ('num_children_required__isnull', True)), models.Q(('node_type', 'group'), ('leaf_course__isnull', True), ('num_children_required__isnull', False)), _connector='OR'), name='courses_are_leafs_and_groups_are_nodes')],
            },
        ),
    ]
