# Generated by Django 5.2.7 on 2025-12-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='antirequisite_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='corequisite_text',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisite_text',
        ),
    ]
