# Generated by Django 5.2.7 on 2025-12-26 02:11

import django.contrib.postgres.fields
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_antirequisite_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserequisitenode',
            name='leaf_course',
        ),
        migrations.RemoveField(
            model_name='courserequisitenode',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='courserequisitenode',
            name='target_course',
        ),
        migrations.AddField(
            model_name='course',
            name='antirequisites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='course',
            name='corequisites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='CoursePrerequisiteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_type', models.CharField(choices=[('group', 'Group'), ('course', 'Course')], max_length=8)),
                ('num_children_required', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('leaf_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.courseprerequisitenode')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_nodes', to='courses.course')),
            ],
        ),
    ]
