# Generated by Django 5.2.7 on 2025-12-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_courserequisitenode_leaf_course_and_more'),
        ('progress', '0002_remove_usercoursepathnode_requisite_node_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRequisiteNode',
        ),
        migrations.AddIndex(
            model_name='courseprerequisitenode',
            index=models.Index(fields=['target_course', 'parent'], name='courses_cou_target__cb8161_idx'),
        ),
        migrations.AddIndex(
            model_name='courseprerequisitenode',
            index=models.Index(fields=['tree_id', 'lft'], name='courses_courseprerequisitea6c1'),
        ),
        migrations.AddConstraint(
            model_name='courseprerequisitenode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('node_type', 'course'), ('leaf_course__isnull', False), ('num_children_required__isnull', True)), models.Q(('node_type', 'group'), ('leaf_course__isnull', True), ('num_children_required__isnull', False)), _connector='OR'), name='courses_are_leafs_and_groups_are_nodes'),
        ),
    ]
