# Generated by Django 5.2.7 on 2025-12-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_delete_courserequisitenode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='offered_next_term',
        ),
    ]
