# Generated by Django 5.2.7 on 2025-12-26 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_offered_next_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('math', 'Math'), ('non_math', 'Non-Math'), ('cs', 'CS'), ('hum', 'Humanities'), ('ss', 'Social Sciences'), ('ps', 'Pure Sciences'), ('as', 'Applied Sciences'), ('comm1', 'Communications List 1'), ('comm2', 'Communications List 2')], max_length=32), blank=True, default=list, size=None),
        ),
    ]
