# Generated by Django 5.2.7 on 2025-12-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='antirequisites',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='corequisites',
            field=models.TextField(),
        ),
    ]
