# Generated by Django 5.2.7 on 2025-12-23 18:44

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='start_year',
            field=models.PositiveSmallIntegerField(default=users.utils.current_year),
        ),
    ]
